# Generated by Django 5.2.1 on 2025-11-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_conductor', models.CharField(max_length=100)),
                ('apellidos_conductor', models.CharField(max_length=100)),
                ('cedula_conductor', models.CharField(max_length=20, unique=True)),
                ('autorizacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlanillasRunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_planilla', models.IntegerField()),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('placa', models.CharField(db_index=True, max_length=20)),
                ('fecha_inicio_viaje', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_viaje', models.DateTimeField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento_conductor', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula_conductor', models.CharField(blank=True, max_length=20, null=True)),
                ('regresa_con_contratante', models.CharField(blank=True, max_length=5, null=True)),
                ('pasajeros', models.IntegerField(blank=True, null=True)),
                ('tipo_documento_pasajero', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula_pasajero', models.CharField(blank=True, max_length=20, null=True)),
                ('contratante', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanillasVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_factura', models.IntegerField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('pagar_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
                ('iva_factura', models.IntegerField(blank=True, null=True)),
                ('total_factura', models.IntegerField(blank=True, null=True)),
                ('cajero', models.CharField(blank=True, max_length=100, null=True)),
                ('caja', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('movil', models.CharField(blank=True, max_length=20, null=True)),
                ('placa', models.CharField(db_index=True, max_length=20)),
                ('concepto', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_concepto', models.CharField(blank=True, max_length=50, null=True)),
                ('corte_concepto', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('sobtotal_concepto', models.IntegerField(blank=True, null=True)),
                ('iva_concepto', models.IntegerField(blank=True, null=True)),
                ('total_concepto', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('linea', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConductorAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_indefinida', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='planillas.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='planillas.vehiculo')),
            ],
            options={
                'unique_together': {('conductor', 'vehiculo')},
            },
        ),
    ]
