# Generated by Django 5.2.1 on 2025-11-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='Vehiculo_planillas',
        ),
    ]
