# Generated by Django 5.2.1 on 2025-11-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0002_rename_vehiculo_vehiculo_planillas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo_planillas',
            new_name='Vehiculo',
        ),
    ]
