# Generated by Django 5.2.1 on 2025-11-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0003_rename_vehiculo_planillas_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillasrunt',
            name='numero_planilla',
            field=models.CharField(max_length=50),
        ),
    ]
