# Generated by Django 5.2.1 on 2025-11-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0004_alter_planillasrunt_numero_planilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillasrunt',
            name='regresa_con_contratante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
