# Generated by Django 5.1 on 2024-10-07 15:21

import django.db.models.deletion
import vehiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lavado',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='lavado',
            name='tipo_lavado',
        ),
        migrations.RemoveField(
            model_name='lavado',
            name='valor',
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo_lavado', models.CharField(max_length=100)),
                ('tiempo', models.TimeField()),
                ('valor', models.FloatField()),
                ('imagenes', models.ImageField(upload_to=vehiculos.models.get_image_upload_path)),
                ('cliente_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.cliente')),
                ('placa_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
