# Generated by Django 5.1 on 2024-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
