# Generated by Django 5.1 on 2024-10-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_lavado_imagenes_remove_lavado_tipo_lavado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='encargado',
            field=models.CharField(default='Sin Asignar', max_length=100),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='estado',
            field=models.CharField(default='En Espera', max_length=50),
        ),
    ]
