# Generated by Django 5.1 on 2024-10-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_recepcion_encargado_recepcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='en_lavado',
            field=models.BooleanField(default=False),
        ),
    ]
