# Generated by Django 5.1 on 2024-10-07 20:28

import django.db.models.deletion
import vehiculos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_recepcion_en_lavado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo_lavado', models.CharField(max_length=100)),
                ('tiempo', models.TimeField()),
                ('valor', models.FloatField()),
                ('imagenes', models.ImageField(upload_to=vehiculos.models.get_image_upload_path)),
                ('estado', models.CharField(max_length=100)),
                ('cliente_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.cliente')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('placa_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
