# Generated by Django 5.1 on 2024-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='inicio_lavado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
