# Generated by Django 5.1 on 2024-10-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_recepcion_inicio_lavado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
