# Generated by Django 5.1 on 2024-10-08 11:56

import django.db.models.deletion
import vehiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_vehiculo_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcion',
            name='imagenes',
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=vehiculos.models.get_image_upload_path)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.recepcion')),
            ],
        ),
    ]
