# Generated by Django 5.1 on 2024-10-08 12:12

import vehiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_remove_recepcion_imagenes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='imagenes',
            field=models.ImageField(null=True, upload_to=vehiculos.models.get_image_upload_path),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
