# Generated by Django 5.1 on 2024-10-08 12:27

import vehiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0010_recepcion_imagenes_delete_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepcion',
            old_name='imagenes',
            new_name='imagen_1',
        ),
        migrations.AddField(
            model_name='recepcion',
            name='imagen_2',
            field=models.ImageField(null=True, upload_to=vehiculos.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='imagen_3',
            field=models.ImageField(null=True, upload_to=vehiculos.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='imagen_4',
            field=models.ImageField(null=True, upload_to=vehiculos.models.get_image_upload_path),
        ),
    ]
