# Generated by Django 5.1 on 2024-10-08 13:13

import vehiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0011_rename_imagenes_recepcion_imagen_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='historial',
            name='en_lavado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historial',
            name='imagen_1',
            field=models.ImageField(null=True, upload_to=vehiculos.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='historial',
            name='imagen_2',
            field=models.ImageField(null=True, upload_to=vehiculos.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='historial',
            name='imagen_3',
            field=models.ImageField(null=True, upload_to=vehiculos.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='historial',
            name='imagen_4',
            field=models.ImageField(null=True, upload_to=vehiculos.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='historial',
            name='inicio_lavado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='encargado',
            field=models.CharField(default='Sin Asignar', max_length=100),
        ),
        migrations.AlterField(
            model_name='historial',
            name='estado',
            field=models.CharField(default='En Espera', max_length=50),
        ),
    ]
