# Generated by Django 5.1 on 2024-10-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0018_delete_placaconvenio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convenio',
        ),
    ]
