# Generated by Django 5.2.1 on 2025-11-09 09:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, help_text='Porcentaje mensual de interés (ej. 2.5 para 2.5%)', max_digits=5)),
                ('cuotas', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado')], default='Activo', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='contratos.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='contratos.vehiculo_contratos')),
            ],
        ),
        migrations.CreateModel(
            name='PagoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuota_numero', models.PositiveIntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='creditos.credito')),
            ],
        ),
    ]
