# Generated by Django 5.2.1 on 2025-11-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocredito',
            name='tipo_pago',
            field=models.CharField(choices=[('cuota', 'Pago de cuota'), ('abono', 'Abono a capital')], default='cuota', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagocredito',
            name='cuota_numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
