# Generated by Django 5.2.1 on 2025-11-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_pagocredito_tipo_pago_alter_pagocredito_cuota_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credito',
            old_name='valor',
            new_name='valor_inicial',
        ),
    ]
