# Generated by Django 5.2.1 on 2025-11-09 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_rename_valor_credito_valor_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('abono_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuota_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_restante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagada', models.BooleanField(default=False)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_credito', to='creditos.credito')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('credito', 'numero')},
            },
        ),
    ]
