# Generated by Django 5.2.1 on 2025-11-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_cuotacredito'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuotacredito',
            unique_together=set(),
        ),
    ]
