# Generated by Django 5.2.1 on 2025-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0005_alter_cuotacredito_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotacredito',
            options={},
        ),
        migrations.AddField(
            model_name='cuotacredito',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Mora', 'En mora')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('En mora', 'En mora'), ('Cobro jurídico', 'Cobro jurídico'), ('Finalizado', 'Finalizado')], default='Activo', max_length=20),
        ),
    ]
