# Generated by Django 5.2.1 on 2025-11-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('creditos', '0006_alter_cuotacredito_options_cuotacredito_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='aprobaciones/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.vehiculo_contratos')),
            ],
        ),
    ]
