# Generated by Django 5.2.1 on 2025-11-14 12:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_aprobacioncredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacioncredito',
            name='estado',
            field=models.CharField(choices=[('En Estudio', 'En Estudio'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Estudio', max_length=20),
        ),
        migrations.CreateModel(
            name='ServicioCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('seguro', 'Seguro Todo Riesgo'), ('gps', 'GPS')], max_length=20)),
                ('valor_anual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Vencido', 'Vencido')], default='Pendiente', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='creditos.credito')),
            ],
            options={
                'ordering': ['fecha_inicio'],
                'unique_together': {('credito', 'tipo', 'fecha_inicio')},
            },
        ),
    ]
