# Generated by Django 5.2.1 on 2025-11-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_usuario_documento1_usuario_documento2_and_more'),
        ('creditos', '0008_alter_aprobacioncredito_estado_serviciocredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='interes',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas', models.PositiveIntegerField()),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Estudio', 'En estudio'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Estudio', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.vehiculo_contratos')),
            ],
        ),
    ]
