# Generated by Django 5.2.1 on 2025-11-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0009_alter_credito_interes_solicitudcredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='interes_moratorio',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Interés moratorio anual (%)', max_digits=5),
            preserve_default=False,
        ),
    ]
