# Generated by Django 5.2.1 on 2025-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0010_credito_interes_moratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocredito',
            name='cobro_juridico_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pagocredito',
            name='interes_moratorio_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
