# Generated by Django 5.2.1 on 2025-12-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0011_pagocredito_cobro_juridico_pagado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombrePrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('T.I', 'Tarjeta de Identidad'), ('NIT', 'NIT'), ('P.T', 'Pasaporte')], max_length=5)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('direccion_prenda', models.CharField(max_length=200)),
            ],
        ),
    ]
