# Generated by Django 5.2.1 on 2025-12-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0012_nombreprendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='prenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='creditos.nombreprendas'),
        ),
    ]
