# Generated by Django 5.2.1 on 2025-12-29 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0013_solicitudcredito_prenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='recibos/')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='creditos.credito')),
                ('pagos', models.ManyToManyField(related_name='recibos', to='creditos.pagocredito')),
            ],
        ),
    ]
