# Generated by Django 5.2.1 on 2026-01-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0014_recibopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='valor_aprobado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
