# Generated by Django 5.2.1 on 2026-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0015_solicitudcredito_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocredito',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagocredito',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
