# Generated by Django 5.2.1 on 2026-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0016_pagocredito_anulado_pagocredito_fecha_anulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=1072)),
            ],
        ),
        migrations.AddField(
            model_name='recibopago',
            name='numero_recibo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
