# Generated by Django 5.1 on 2024-11-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_nuevo', models.BooleanField(default=True)),
                ('traspaso', models.BooleanField(default=False)),
                ('documentos_al_dia', models.BooleanField(default=False)),
                ('entrega_comercial', models.BooleanField(default=False)),
                ('desembolso', models.BooleanField(default=False)),
                ('saldo', models.BooleanField(default=False)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.vehiculo_contratos')),
            ],
        ),
    ]
