# Generated by Django 5.2.1 on 2025-11-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='documento1',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento2',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento3',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento4',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
