# Generated by Django 5.2.1 on 2026-02-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_usuario_documento1_usuario_documento2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='archivo_adicional',
            field=models.FileField(blank=True, null=True, upload_to='documentos/adicionales/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sede',
            field=models.CharField(choices=[('Taxi Cupos', 'Taxi Cupos'), ('Green Wash', 'Green Wash'), ('Operadora', 'Operadora'), ('Financiera', 'Financiera')], max_length=50, null=True),
        ),
    ]
